"""Generate narrow, inactive policy drafts from redacted events."""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Any

import yaml

from toolpermit.audit.store import EventRecord
from toolpermit.canonical import canonical_bytes
from toolpermit.redaction import is_redacted


@dataclass(frozen=True)
class Suggestion:
    content: str
    warnings: tuple[str, ...]
    evidence_event_ids: tuple[str, ...]


def _safe_scalar_constraints(arguments: dict[str, Any]) -> dict[str, dict[str, object]]:
    constraints: dict[str, dict[str, object]] = {}
    for key, value in sorted(arguments.items()):
        if is_redacted(value):
            continue
        if value is None or isinstance(value, (bool, int, float, str)):
            constraints[key] = {"exact": value}
    return constraints


def suggest_policy(events: tuple[EventRecord, ...]) -> Suggestion:
    ordered = sorted(
        events,
        key=lambda event: (
            event.tool_name,
            event.schema_fingerprint,
            canonical_bytes(event.arguments),
            event.id,
        ),
    )
    unique: dict[tuple[str, str, bytes], list[EventRecord]] = {}
    for event in ordered:
        key = (event.tool_name, event.schema_fingerprint, canonical_bytes(event.arguments))
        unique.setdefault(key, []).append(event)

    rules: list[dict[str, object]] = []
    warnings: list[str] = []
    evidence: list[str] = []
    for (tool_name, _fingerprint, _arguments_key), examples in unique.items():
        arguments = examples[0].arguments
        constraints = _safe_scalar_constraints(arguments)
        suffix = hashlib.sha256(canonical_bytes(arguments)).hexdigest()[:10]
        rule_id = f"suggested-{tool_name.replace('/', '-').replace('.', '-')}-{suffix}"[:128]
        if not constraints:
            warnings.append(
                f"{rule_id}: no safe scalar constraints were available; review this broad tool rule"
            )
        event_ids = sorted(example.id for example in examples)
        evidence.extend(event_ids)
        rules.append(
            {
                "id": rule_id,
                "action": "allow",
                "explanation": f"Observed in events: {', '.join(event_ids)}.",
                "match": {"tool": tool_name, "arguments": constraints},
            }
        )

    document = {"version": 1, "default": "ask", "rules": rules}
    body = yaml.safe_dump(document, sort_keys=False, allow_unicode=True)
    header = (
        "# Generated by ToolPermit. This policy is inactive until explicitly selected.\n"
        "# Review every allow rule and run `toolpermit replay` before enforcement.\n"
    )
    return Suggestion(
        content=header + body,
        warnings=tuple(sorted(warnings)),
        evidence_event_ids=tuple(sorted(set(evidence))),
    )

